name = "bosconfts/pix-oracle-settlement"
version = "0.0.1"
compiler = "v1.1.21"
plutus = "v3"
license = "MIT"
description = "PIX Oracle Settlement — Charli3 Hackathon 2026"

[repository]
user = "bosconfts"
project = "pix-oracle-settlement"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
